import json
from core.constants import *

from core.ai.ollama_client import OllamaClient
from core.ai.prompt_engine import PromptEngine
from core.ai.cad_parser import CADParser
from core.ai.feedback_loop import FeedbackLoopEngine
from core.ai.streaming_ollama import StreamingOllama
from core.ai.stream_json_builder import StreamJSONBuilder

class AIService:

    def __init__(self, context):
        self.context = context
        self.event_bus = context.event_bus
        self.client = OllamaClient(model="gemma4:31b-cloud")
        self.feedback_engine = FeedbackLoopEngine(context)
        self.stream_client = StreamingOllama()

        # Listen for generate requests
        self.event_bus.subscribe(
            TOOL_GENERATE,
            self.on_generate_request
        )

    ########################################################

    def on_generate_request(self, _=None):

        self.context.logger.info("AI Service: Generate request received")

        prompt = self._get_last_prompt()

        if not prompt:
            self.context.logger.info("No prompt found")
            return

        self.context.task_manager.submit(
            "AI Generation",
            self.generate_model,
            prompt
        )

    ########################################################

    def _get_last_prompt(self):

        # Temporary placeholder (chat integration later)
        return getattr(self.context.design_state, "last_prompt", None)

    ########################################################

    def generate_model(self, prompt):

        self.context.logger.info("Using Design Copilot Brain")

        try:
            design = self.context.design_brain.design(prompt)
            
            # Store state
            self.context.design_state.set_model(
                design["name"],
                design["parameters"]
            )

            self.context.design_state.cad_code = str(design)

            self.event_bus.publish(
                MODEL_GENERATED,
                design
            )

            self.event_bus.publish(
                STATUS_CHANGED,
                "Design generated by Copilot"
            )

            return design
        except Exception as e:
            self.context.logger.error(f"Error generating model: {e}")
            self.event_bus.publish(
                STATUS_CHANGED,
                f"Error: {str(e)}"
            )
            return None
    def stream_generate(self, prompt, on_update):

        builder = StreamJSONBuilder()

        full_prompt = PromptEngine.build_cad_prompt(prompt)

        for token in self.stream_client.stream(full_prompt):

            builder.add_token(token)

            partial = builder.try_parse()

            if partial:

                on_update(partial)