# Application

APP_STARTED = "APP_STARTED"

APP_EXIT = "APP_EXIT"

# Chat

PROMPT_SUBMITTED = "PROMPT_SUBMITTED"

AI_RESPONSE = "AI_RESPONSE"

# CAD

GENERATE_MODEL = "GENERATE_MODEL"

MODEL_GENERATED = "MODEL_GENERATED"

MODEL_UPDATED = "MODEL_UPDATED"

PARAMETERS_UPDATED = "PARAMETERS_UPDATED"

# Project

PROJECT_NEW = "PROJECT_NEW"

PROJECT_OPEN = "PROJECT_OPEN"

PROJECT_SAVE = "PROJECT_SAVE"

PROJECT_RESET = "PROJECT_RESET"

# Export

EXPORT_STL = "EXPORT_STL"

EXPORT_STEP = "EXPORT_STEP"

# Status

STATUS_CHANGED = "STATUS_CHANGED"
# Worker

TASK_STARTED = "TASK_STARTED"

TASK_COMPLETED = "TASK_COMPLETED"

TASK_FAILED = "TASK_FAILED"
# Commands

COMMAND_EXECUTED = "COMMAND_EXECUTED"

COMMAND_UNDO = "COMMAND_UNDO"

COMMAND_REDO = "COMMAND_REDO"
# Toolbar Events

TOOL_NEW = "TOOL_NEW"
TOOL_OPEN = "TOOL_OPEN"
TOOL_SAVE = "TOOL_SAVE"

TOOL_UNDO = "TOOL_UNDO"
TOOL_REDO = "TOOL_REDO"

TOOL_GENERATE = "TOOL_GENERATE"

TOOL_EXPORT_STL = "TOOL_EXPORT_STL"
TOOL_EXPORT_STEP = "TOOL_EXPORT_STEP"

TOOL_SETTINGS = "TOOL_SETTINGS"
WINDOW_WIDTH = 1700
WINDOW_HEIGHT = 950

MIN_WINDOW_WIDTH = 1400
MIN_WINDOW_HEIGHT = 800